### PR TITLE
Fix when generating a PDF report, the open report button in safari does not work

### LINKED ISSUE #7018: When generating a PDF report, the open report button in safari does not work
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.1 | xyzw | Safari |

**Description**

When generating a PDF report, the open report button in safari does not work

**Steps to reproduce**
1. Go to some module
2. Click on generate pdf report
3. Click on open report button

**Screenshots**

https://github.com/user-attachments/assets/1e2c9e30-2441-4f39-8f94-fd596b64e189

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

Fix when generating a PDF report, the open report button in safari does not work

### Issues Resolved

#7018 

### Evidence

https://github.com/user-attachments/assets/fe9b1073-f442-489a-8b9c-99dd2244d17c

### Test
[Provide instructions to test this PR

- Go to some module

- Click on generate pdf report

- Click on open report button

### Check List
- [x] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: plugins/main/public/react-services/reporting.js [hunk 1]
```diff
@@ -94,12 +94,24 @@ export class ReportingService {
...
+                    `/reports/${filename}`,
+                  );
+
+                  // Then assign the URL to the new tab
+                  windowReference.location = url;
+                } else {
+                  // If the tab is locked, it displays an alert to the user.
+                  alert('The tab was blocked. Please enable pop-up windows.');
+                }
+              }}
```
Comment (Desvelao) [inline plugins/main/public/react-services/reporting.js:114]: **thought**: I see you changed to `window.open`. For this case, we could try a cleaner solution using a link instead of manage the access to the report with a `onClick`. Could you try it?

In the case we implement the proposed solution in the `onClick`, there are more usages of `window.open` that could be failing in Safari too. We should review them.

File: CHANGELOG.md [hunk 2]
```diff
@@ -21,6 +21,7 @@ All notable changes to the Wazuh app project will be documented in this file.
 - Fixed missing options depending on agent operating system in the agent configuration report [#6983](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6983)
 - Fixed an style that affected the Discover plugin [#6989](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6989)
 - Fixed a problem updating the API host registry in the GET /api/check-stored-api [#6995](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6995)
+- Fixed, when generating a PDF report, the open report button in safari does not work [#7019](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7019)
```
Comment (Desvelao) [inline CHANGELOG.md:24]:
```suggestion
- Fixed the `Open report` button does not work on Safari [#7019](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7019)
```

Comment (chantal-kelm) [reply CHANGELOG.md]: I have corrected the changelog by mentioning the two changes I have made [649e7d9](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7019/commits/649e7d9b12dd805cc9fe4f18bd1f976356ee23da)

- Fixed the `Open report` button of the toast and the `Download report` icon of the reporting table in Safari [#7019](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7019)

**Review by Machi3mfl — APPROVED** [review]
https://github.com/user-attachments/assets/5bf64e7c-3478-4dc8-897c-9cb3cac1bf57

**Review by asteriscos — COMMENTED** [review]
CR: :green_circle: 
Test: :green_circle: 


https://github.com/user-attachments/assets/cc9116b2-5dbd-4d17-9260-d0c73347a5e3

**Review by asteriscos — APPROVED** [review]
