### PR TITLE
Fix readonly user cannot read statistics

### LINKED ISSUE #6988: Readonly users can not see wazuh-statistics-* indices
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | xyzw | Chrome, Firefox, Safari, etc |

**Description**
A readonly user can not see data related to statistics.

**Preconditions**
1. Create a readonly user following https://documentation.wazuh.com/4.9/user-manual/user-administration/rbac.html#creating-and-setting-a-wazuh-read-only-user
2. Ensure there indices related to `wazuh-statistics-*` and the index pattern is created

**Steps to reproduce**
1. Login with the readonly user and go to `Statistics` application.
2. A message is displayed related to there are no indices

**Screenshots**
image

**Additional context**
The `GET /elastic/statistics` API request is failing.

image

This is probably related to the user permissions that can not do the action that is executed in the endpoint.

The logic related to the API request to check the existence of indices, could be replaced a similar to `Vulnerabilities Detection > Dashboard`.

### PR DESCRIPTION
**Pull request by Tostti**
### Description
This PR fixes a bug where the readonly users could not access the statistics dashboard
 
### Issues Resolved
#6988

### Evidence
image

### Test
**Preconditions**
1. Create a readonly user following https://documentation.wazuh.com/4.9/user-manual/user-administration/rbac.html#creating-and-setting-a-wazuh-read-only-user
2. Ensure there indices related to `wazuh-statistics-*` and the index pattern is created

**Steps to reproduce**
1. Login with the readonly user and go to `Statistics` application.
2. Verify that no errors are shown and the dashboards are visible

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: plugins/main/public/react-services/check-index.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import { SavedObject } from '.';
+
+export async function checkExistenceIndices(indexPatternId: string) {
```
Comment (guidomodarelli) [inline plugins/main/public/react-services/check-index.ts:3]: The "check" prefix can be ambiguous; it may be clearer to use the "verify" prefix instead, such as `verifyExistenceIndices`.

File: plugins/main/public/react-services/check-index.ts
Comment (guidomodarelli) [inline plugins/main/public/react-services/check-index.ts:1]: The "check" prefix can be ambiguous; it may be clearer to use the "verify" prefix instead, such as verify-index-exists.

File: plugins/main/server/routes/wazuh-elastic.test.ts [hunk 2]
```diff
@@ -3,10 +3,19 @@
 import axios from 'axios';
 import { PLUGIN_PLATFORM_REQUEST_HEADERS } from '../../common/constants';
 
-function buildAxiosOptions(method: string, path: string, data: any = {}, headers: any = {}) {
+function buildAxiosOptions(
+  method: string,
+  path: string,
+  data: any = {},
+  headers: any = {},
```
Comment (guidomodarelli) [inline plugins/main/server/routes/wazuh-elastic.test.ts:10]: We can use `Record<string, unknown>` instead

File: plugins/main/server/controllers/wazuh-elastic.ts [hunk 3]
```diff
@@ -681,6 +681,23 @@ export class WazuhElasticCtrl {
     }
   }
 
+  async statisticsIndexPattern(
+    context: RequestHandlerContext,
+    request: OpenSearchDashboardsRequest,
```
Comment (guidomodarelli) [inline plugins/main/server/controllers/wazuh-elastic.ts:686]: It's not being used, please delete it.

File: plugins/main/public/react-services/check-index.ts (hunk 1 above)
Comment (Tostti) [reply plugins/main/public/react-services/check-index.ts]: Solved in https://github.com/wazuh/wazuh-dashboard-plugins/pull/7001/commits/7e10153c2e0817a9ffbb5796031906781d7d6779

File: plugins/main/public/react-services/check-index.ts
Comment (Tostti) [reply plugins/main/public/react-services/check-index.ts:1]: Solved in https://github.com/wazuh/wazuh-dashboard-plugins/pull/7001/commits/7e10153c2e0817a9ffbb5796031906781d7d6779

File: plugins/main/server/routes/wazuh-elastic.test.ts (hunk 2 above)
Comment (Tostti) [reply plugins/main/server/routes/wazuh-elastic.test.ts:10]: Will not change this as it is out of the scope of this PR

File: plugins/main/public/controllers/management/components/management/statistics/statistics-overview.js [hunk 4]
```diff
@@ -237,12 +243,41 @@ export default compose(
...
+        // Check the existence of related index pattern
+        const existIndexPattern = await verifyExistenceIndexPattern(
+          indexPatternID,
+        );
         setLoading(true);
-        const data = await WzRequest.genericReq('GET', '/elastic/statistics');
-        setExistStatisticsIndices(data.data);
+
+        // If the index pattern does not exist, then check the existence of index
+        if (existIndexPattern?.error?.statusCode === 404) {
```
Comment (guidomodarelli) [inline plugins/main/public/controllers/management/components/management/statistics/statistics-overview.js:259]: You can use `HTTP_STATUS_CODES.NOT_FOUND` from `plugins/main/common/constants.ts`

Comment (Tostti) [reply plugins/main/public/controllers/management/components/management/statistics/statistics-overview.js]: Solved in https://github.com/wazuh/wazuh-dashboard-plugins/pull/7001/commits/03f9fa3df32d6f5ae61a0d2259fff878bb96290f

**Review by guidomodarelli — DISMISSED** [review]

**Review by guidomodarelli — APPROVED** [review]
CR :green_circle: 
TEST :green_circle: 


https://github.com/user-attachments/assets/cf89fb5b-cd6e-4b62-9da1-e889e3f63940

**Review by guidomodarelli — APPROVED** [review]
CR :green_circle: 
TEST :green_circle: 


https://github.com/user-attachments/assets/a54cf6d4-1339-4d81-862c-120b987c5c00

**Review by asteriscos — APPROVED** [review]
CR: :green_circle: 
Test: :green_circle: 

image
