### PR TITLE
Fix some problems related to IT Hygiene

### LINKED ISSUE #7450: Bugs found in global queries
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| X.Y.Z | xyzw | Chrome, Firefox, Safari, etc |

**Description**

Some bugs were found in the exploration of global queries:

- `host.memory.used` is a percentage and should not be formatted
- `host.memory.total` is using a wrong unit
Image

- `package.architecture` could not be a usual field. Consider the deletion as default column (confirm)
Image

- `States` is specific to Linux, consider to replace the visualization for another one more general
Image

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request 

# Changes
- Remove Arhitecture selector from System > Hardware
- Remove `package.architecture` as default column in Packages > Packages
- Replace States viualization ain IT Hygiene > Dashboard and Processes > Processses
- Fix visualization of Global packets loss rate

### Issues Resolved
#7450

### Evidence
image
image
image
image
image

### Test

# wdp-pr-7461

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Ensure there is no Arhitecture selector in System > Hardware | :black_circle: | :black_circle: | :black_circle: |
| Ensure the package.architecture field is not set as default column in of the table in Packages > Packages | :black_circle: | :black_circle: | :black_circle: |
| Ensure the visualization of Global packets loss rate represents the expected value and has no too much decimals | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Ensure there is no Arhitecture selector in System > Hardware

</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the package.architecture field is not set as default column in of the table in Packages > Packages</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Ensure the visualization of Global packets loss rate represents the expected value and has no too much decimals</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: plugins/main/public/components/common/hocs/with-index-pattern.tsx [hunk 1]
```diff
@@ -242,6 +242,12 @@ const fieldMappers = {
   // integer, remove thousands and decimals separator thorugh the params.pattern
   integer: ({ type }) =>
     type === 'number' ? { id: 'number', params: { pattern: '0' } } : undefined,
+  percent: ({ type }) => {
+    console.log({ type });
```
Comment (yenienserrano) [inline plugins/main/public/components/common/hocs/with-index-pattern.tsx:246]: Maybe this can be deleted

File: plugins/main/public/components/common/hocs/with-index-pattern.tsx [hunk 2]
```diff
@@ -250,6 +256,7 @@ export function mapFieldsFormat(expectedFields: {
   return {
     mapSavedObjectAttributesCreation: ({ fields }) => {
       const fieldsToMap = Object.keys(expectedFields);
+      console.log({ fieldsToMap });
```
Comment (yenienserrano) [inline plugins/main/public/components/common/hocs/with-index-pattern.tsx:259]: Maybe this can be deleted

**Comment by guidomodarelli** [comment]
### Test

# wdp-pr-7461

Legend:
⚫ => The test hasn't started yet.
🟢 => All checks passed.
🟡 => There is at least one expected fail or skipped test and no failures.
🔴 => There is at least one failed check.
⚪ => Doesn't apply.
🔧 => Request changes.
❓ => Needs more information. 

## UI

| Test | Chrome | Firefox | 
| --- |  --- | --- | 
| Ensure there is no Arhitecture selector in System > Hardware | ⚫ | ⚫
| Ensure the package.architecture field is not set as default column in of the table in Packages > Packages | ⚫ | ⚫
| Ensure the visualization of Global packets loss rate represents the expected value and has no too much decimals | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary> ⚫ Ensure there is no Architecture selector in System > Hardware


</summary>

Chrome - ⚫

image

Firefox - ⚫ 

image


</details>

<details>
<summary> ⚫ Ensure the package.architecture field is not set as default column in of the table in Packages > Packages</summary>

Chrome - ⚫

image

Firefox - ⚫

image



</details>

<details>
<summary>:black_circle: Ensure the visualization of Global packets loss rate represents the expected value and has no too much decimals</summary>

Chrome - ⚫

Firefox - ⚫


</details>

**Review by guidomodarelli — APPROVED** [review]
Legend:
⚫ => The test hasn't started yet.
🟢 => All checks passed.
🟡 => There is at least one expected fail or skipped test and no failures.
🔴 => There is at least one failed check.
⚪ => Doesn't apply.
🔧 => Request changes.
❓ => Needs more information. 

# 🧪 Test 2025/05/26

CR 🟢
TEST 🟢

**Review by guidomodarelli — APPROVED** [review]
LGTM! 🟢

**Review by yenienserrano — APPROVED** [review]
CR: 🟢
Test: 🟢
