### PR TITLE
Agent view Mitre ATT&CK exception

### LINKED ISSUE #7064: Agent view Mitre ATT&CK exception
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.10.0 | 00 | Chrome, Firefox, Safari, etc |

**Description**
If a user clicks the Mitre ATT&CK card actions an exception is thrown.

**Screenshots**
Peek 2024-10-03 17-49

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

Fixed Exception in Mitre ATT&CK Agent View.

The ID redirects, Tactics, dashboard icon, and Event Icon redirects were fixed within the flyout and are now redirecting correctly.

The card not display information when the flyout was opened.
 
### Issues Resolved

#7064 

### Evidence

https://github.com/user-attachments/assets/5df0ce2e-4e17-4d63-9b7a-fc5846e8e9ed

https://github.com/user-attachments/assets/813ab1d9-d65d-4d3b-b77d-f0d70a7886d9

### Test

- Go to the endpoint summary section, in the MITRE ATT&CK section click on one of the main tactics and then click on a technique, check that the drop down opens correctly.

- Within the flyout check that the ID, Tactics, dashboard icon, and events icon links redirect well.

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by yenienserrano — APPROVED** [review]
LGTM


https://github.com/user-attachments/assets/7dcea27a-0781-42ef-a805-0a0d141d650c

**Review by asteriscos — CHANGES_REQUESTED** [review]
Test: :red_circle: 

The links within the flyout aren't working. Please check this

Peek 2024-10-24 13-41

**Comment by chantal-kelm** [comment]
> Test: 🔴
> 
> The links within the flyout aren't working. Please check this
> 
> Peek 2024-10-24 13-41 [ Peek 2024-10-24 13-41 ](https://private-user-images.githubusercontent.com/9343732/379751796-876ae69b-3086-442b-8b3e-ea0478ff3656.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzk1MDEsIm5iZiI6MTczMDEzOTIwMSwicGF0aCI6Ii85MzQzNzMyLzM3OTc1MTc5Ni04NzZhZTY5Yi0zMDg2LTQ0MmItOGIzZS1lYTA0NzhmZjM2NTYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTgxMzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhmYmE3MWUxZjQ0ZjJkMzU3ZjIyMmE0NGVjMjNmZWQ3NzVhNTg0ZDVkZjU2NzNmM2EzNTdkZmEzYWI3NTA4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hbarw9hz8nkNgwJMVEAUG96rVpfiher5x8fNPUK0I-I) [ ](https://private-user-images.githubusercontent.com/9343732/379751796-876ae69b-3086-442b-8b3e-ea0478ff3656.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzk1MDEsIm5iZiI6MTczMDEzOTIwMSwicGF0aCI6Ii85MzQzNzMyLzM3OTc1MTc5Ni04NzZhZTY5Yi0zMDg2LTQ0MmItOGIzZS1lYTA0NzhmZjM2NTYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTgxMzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhmYmE3MWUxZjQ0ZjJkMzU3ZjIyMmE0NGVjMjNmZWQ3NzVhNTg0ZDVkZjU2NzNmM2EzNTdkZmEzYWI3NTA4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hbarw9hz8nkNgwJMVEAUG96rVpfiher5x8fNPUK0I-I)

Fixed

File: plugins/main/public/components/common/welcome/components/mitre_top/mitre-top.tsx [hunk 1]
```diff
@@ -108,25 +114,48 @@ const MitreTopTacticsTechniques = ({
       setShowTechniqueDetails('');
     };
 
-    const openDiscover = (e, techniqueID) => {
-      NavigationService.getInstance().navigateToModule(e, 'overview', {
-        tab: 'mitre',
-        tabView: 'discover',
-        filters: { 'rule.mitre.id': techniqueID },
+    const goToDashboardWithFilter = async (e, techniqueID) => {
+      const indexPatternId = AppState.getCurrentPattern();
```
Comment (Desvelao) [inline plugins/main/public/components/common/welcome/components/mitre_top/mitre-top.tsx:118]: **suggestion**: this should be using the data source instead of trusting the index pattern ID is obtained through the `AppState` service.

Comment (Desvelao) [reply plugins/main/public/components/common/welcome/components/mitre_top/mitre-top.tsx:118]: The data source instance is created in the events table that is rendered by the accordion that contains the links. This could imply a refactor to extract the instance of the data source or communicate to the parents. So we could use this approach for now.

**Comment by Desvelao** [comment]
# :green_circle: Test

Go to Events
image
image

Go to Dashboard:
image
image

Go to Intelligence  (technique)
image
image

Go to Intelligence (tactic)
image
image

**Review by Desvelao — DISMISSED** [review]
LGTM!
