### PR TITLE
Filter deprecated actions

### LINKED ISSUE #7031: Security policies exception
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.2 | xyzw | Chrome, Firefox, Safari, etc |

**Description**
Some security policies throw an exception when trying to view the details in the edit flyout.

**Screenshots**

Peek 2024-09-27 19-20

**Additional context**

Related code:
https://github.com/wazuh/wazuh-dashboard-plugins/blob/master/plugins/main/public/components/security/policies/edit-policy.tsx#L162

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
The goal of this pull request is to filter deprecated / not listed actions in Wazuh API `/security/actions` endpoint. 
 
### Issues Resolved
Closes #7031 

### Test
- Go to Server management -> Security -> Policies
- Click on the policy that has the `security:revoke` action
- Check it doesn't throw an exception

Peek 2024-10-01 12-41

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Tostti — DISMISSED** [review]
Test 🟢 
image


CR 🟢 


LGTM

File: plugins/main/public/components/security/policies/edit-policy.tsx [hunk 1]
```diff
@@ -130,16 +130,18 @@ export const EditPolicyFlyout = ({ policy, closeFlyout }) => {
...
   }
 
   const loadResources = () => {
     let allResources = [];
-    addedActions.forEach(x => {
-      const res = (availableActions[x.action] || {})['resources'];
-      allResources = allResources.concat(res);
-    });
+    addedActions
+      .filter(x => !!availableActions[x.action]) // Remove configured actions no longer available on the API
```
Comment (guidomodarelli) [inline plugins/main/public/components/security/policies/edit-policy.tsx:140]:
```suggestion
      .filter(x => !!availableActions?.[x.action]) // Remove configured actions no longer available on the API
```

**Review by guidomodarelli — COMMENTED** [review]
Test :green_circle: 
image
