### PR TITLE
Fix exception reading policy_id property of undefined in IT-hygiene

### LINKED ISSUE #6167: IT Hygiene module throws exception reading policy_id property of undefined
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 00 | Chrome, Firefox, Safari, etc |

**Description**
In the Endpoints Summary table, when we click an agent without policies and loads the IT Hygiene view, an exception is thrown because it cannot read the `policy_id` property of an object.
We should handle this case and load all the available information without breaking the view.

**Screenshots**
Peek 2023-11-28 18-51

### PR DESCRIPTION
**Pull request by asteriscos**
### Description
Hi team, this PR fixes a few exceptions when an agent still doesn't have an assigned group or doesn't have any policies.

Also, it segregates Inventory tables into different components and adds a high-order component to guard the properties when an agent doesn't have the operating system information.

Additionally, fixes a bug when selecting and deselecting agents with the `Explore Agent` button.
 
### Issues Resolved
#6167 

### Evidence
image
image

#### Inventory tables when there's no operating system
image

### Test

- Make sure you have an agent without any policy or group assigned: You can achieve this by creating a docker wazuh-agent instance and shutting it down as soon as it registers.
- Go to Endpoints summary
- Select the mentioned agent in the table
- Check the agent view works properly and doesn't throw an exception

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: plugins/main/public/components/common/welcome/components/sca_scan/sca_scan.tsx [hunk 1]
```diff
@@ -209,7 +209,7 @@ export const ScaScan = compose(
                     href={getCore().application.getUrlForApp(
                       configurationAssessment.id,
                       {
-                        path: `#/overview?tab=sca&redirectPolicy=${lastScan.policy_id}`,
+                        path: `#/overview?tab=sca&redirectPolicy=${lastScan?.policy_id}`,
```
Comment (Desvelao) [inline plugins/main/public/components/common/welcome/components/sca_scan/sca_scan.tsx:212]: **thought**: This solves the problem if the `lastScan` variable is undefined or something like that, but for this cause, the button will redirect to `#/overview?tab=sca&redirectPolicy=undefined` that doesn't make sense and could cause problems because the `redirectPolicy` query parameter causes a specific policy is selected.

File: plugins/main/public/components/common/welcome/components/sca_scan/sca_scan.tsx [hunk 2]
```diff
@@ -277,7 +277,7 @@ export const ScaScan = compose(
                         href={getCore().application.getUrlForApp(
                           configurationAssessment.id,
                           {
-                            path: `#/overview?tab=sca&redirectPolicy=${lastScan.policy_id}`,
+                            path: `#/overview?tab=sca&redirectPolicy=${lastScan?.policy_id}`,
```
Comment (Desvelao) [inline plugins/main/public/components/common/welcome/components/sca_scan/sca_scan.tsx:280]: **thought**: This solves the problem if the `lastScan` variable is undefined or something like that, but for this cause, the button will redirect to `#/overview?tab=sca&redirectPolicy=undefined` that doesn't make sense and could cause problems because the `redirectPolicy` query parameter causes a specific policy is selected.

File: plugins/main/public/components/common/welcome/components/sca_scan/sca_scan.tsx [hunk 3]
```diff
@@ -220,7 +220,7 @@ export const ScaScan = compose(
               </RedirectAppLinks>
             </EuiFlexItem>
             <EuiFlexItem grow={false} style={{ marginTop: 12 }}>
-              <EuiBadge color='secondary'>{lastScan.policy_id}</EuiBadge>
+              <EuiBadge color='secondary'>{lastScan?.policy_id}</EuiBadge>
```
Comment (Desvelao) [inline plugins/main/public/components/common/welcome/components/sca_scan/sca_scan.tsx:223]: **thought**: This solves the problem if the `lastScan` variable is undefined or something like that, but for this cause, the text could appear as `undefined`. I don't think we want this on the UI.

**Review by Desvelao — CHANGES_REQUESTED** [review]
Review the request changes.

Additionally, add the entry to the changelog.

File: plugins/main/public/components/agents/syscollector/components/network-interfaces-table.tsx [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+import { TableWzAPI } from '../../../common/tables';
+import { WzRequest } from '../../../../react-services';
+import { get as getLodash } from 'lodash';
+import { netifaceColumns } from '../columns';
+
+const sortFieldSuggestion = (a, b) => (a.label > b.label ? 1 : -1);
+
+export const NetworkInterfacesTable = ({ agent }) => {
+  return (
+    <EuiPanel paddingSize='m' style={{ margin: '12px 16px 12px 16px' }}>
```
Comment (Desvelao) [inline plugins/main/public/components/agents/syscollector/components/network-interfaces-table.tsx:13]: **nitpick**: this panel component has different properties of the rest syscollector panels. Is there a reason for this or only forget to replace it?

Comment (asteriscos) [reply plugins/main/public/components/agents/syscollector/components/network-interfaces-table.tsx:13]: Some tables need the `soPlatform` property to determine which column will render, but some tables don't need this property as it does not depend on the operating system to render the information.

**Review by jbiset — APPROVED** [review]
LGMT

## Test :green_circle: 
### Testing 
[evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/e143261a-4ae1-41a1-9fd5-bb8222c6e43b)

#### Not enough hardware or operating system information
Evidence2

#### Agents without SCA scans
image
