### PR TITLE
Fixed displaying not updated data in the SCA inventory table expanded row

### LINKED ISSUE #7543: [BUG] Inconsistent Data Refresh Behavior in Dashboard Table Accordion
**Issue Description**
When using the Wazuh dashboard's event table accordion, I've noticed an inconsistency in data refresh behavior. Specifically, upon clicking the "Refresh" button, the data within the accordion table does not update dynamically. Instead, the displayed content remains static until the accordion is closed and reopened, at which point the updated data is reflected.

Interestingly, this behavior contrasts with the automatic refresh of the "Result" column, where it dynamically transitions from "Failed" with a red dot to "Passed" with a green dot without requiring manual intervention.

**To Reproduce**

0. Define your individual SCA rule in which you check for the presence of a string in a file, but do not create the file (status is then not applicable)
1. Open the Wazuh dashboard.
2. Navigate to the event table accordion.
3. Observe the data within the accordion.
4. Now create the file in the host on which the agent is installed so that the status changes from not applicable to Passed (or failed, depending on the check).
6. Click the "Refresh" button.
7. Note that the data does not update dynamically.
8. Close and reopen the accordion.
9. Observe that the updated data is now reflected.

**Expected behavior**
Upon clicking the "Refresh" button, the data within the event table accordion should update dynamically without requiring manual closure and reopening of the accordion.

**Impact**
This inconsistency in data refresh behavior affects user experience and may lead to confusion regarding the real-time status of events within the dashboard. Resolving this issue would enhance the usability and reliability of the Wazuh dashboard for users relying on up-to-date event information.

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request fixes a problem that allowed displaying not updated data if using the Refresh button in the SCA table row.

Side changes:
- A new component was done that manages the expanded row and is used for SCA inventory table (and other Wazuh server API tables)
- Change the usage of `EuiBasicTable` by the new component that manages the expanded table rows.
- Any change in the items received by the table will cause the expanded rows are collapsed. The previous behavior kept at least one expanded row despite this was in another page.

Built Wazuh server for test: https://github.com/wazuh/wazuh/actions/runs/15735916725
  
### Issues Resolved
#7543

### Evidence

Configuration Assessment > Dashboard
image

Configuration Assessment > Dashboard. Click on the `Refresh` button.
image

MITRE ATT&CK > Framework
image

Security > Roles > Edit role
image

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| In Configuration Assessment > Dashboard, see acheck policy expanding the row, ensure the SCA policy eas executed and the check result changed, then click on the Refresh button. The expanded row should be collapsed and you should see the new result for the check (if this is in the page 1, else you should navigate). Expand the row should display the updated data. | :black_circle: | :black_circle: | :black_circle: |
| In Configuration Assessment > Dashboard, clicking on the table rows of the policy checks should expand the row and display more information. | :black_circle: | :black_circle: | :black_circle: |
| In Configuration Assessment > Dashboard, clicking on the button of the row that expands it should expand the row and display more information. | :black_circle: | :black_circle: | :black_circle: |
| In all the modules of Regulatory compliance/MITRE ATT&CK > Controls, open the flyout details, and expand rows of the table, changing the page or refreshing the query, should collapse the expanded rows. | :black_circle: | :black_circle: | :black_circle: |
| In all the modules of Regulatory compliance/MITRE ATT&CK > Controls, open the flyout details, clicking on the expand row button should expand the event with more information. | :black_circle: | :black_circle: | :black_circle: |
| In Security > Roles > Edit role flyout, clicking on the expand row button, should expand the row. | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: In Configuration Assessment > Dashboard, see acheck policy expanding the row, ensure the SCA policy eas executed and the check result changed, then click on the Refresh button. The expanded row should be collapsed and you should see the new result for the check (if this is in the page 1, else you should navigate). Expand the row should display the updated data.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Configuration Assessment > Dashboard, clicking on the table rows of the policy checks should expand the row and display more information.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Configuration Assessment > Dashboard, clicking on the button of the row that expands it should expand the row and display more information.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In all the modules of Regulatory compliance/MITRE ATT&CK > Controls, open the flyout details, and expand rows of the table, changing the page or refreshing the query, should collapse the expanded rows.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In all the modules of Regulatory compliance/MITRE ATT&CK > Controls, open the flyout details, clicking on the expand row button should expand the event with more information.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: In Security > Roles > Edit role flyout, clicking on the expand row button, should expand the row.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: plugins/main/public/components/common/tables/table.tsx [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+              ((onClick, item) => {
+                return (...args) => {
+                  toggleExpandedRow(item);
+                  onClick?.(...args);
+                };
+              }),
+          })
+        : internalRowProps;
+
+      const itemIdToExpandedRowMap =
```
Comment (Firefly0) [inline plugins/main/public/components/common/tables/table.tsx:92]: this const will be recreated at each render - and it looks expensive, performance wise

For this particular const is best if you use useMemo() - it will recreate the const only when something changes

File: plugins/main/public/components/common/tables/table.tsx [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+  );
+}
+
+function expandableItemGetId(item, itemId: string) {
+  return String(get(item, itemId));
+}
+
+export type TableBasicManageExpandedItemsProps = EuiBasicTableProps & {
+  itemId?: string;
+  expandableRowButtonSide: 'left' | ' right';
```
Comment (Firefly0) [inline plugins/main/public/components/common/tables/table.tsx]: typo? 
```suggestion
  expandableRowButtonSide: 'left' | 'right';
```

Comment (Desvelao) [reply plugins/main/public/components/common/tables/table.tsx]: Thank you so much. I fixed it here: https://github.com/wazuh/wazuh-dashboard-plugins/pull/7544/commits/c13c9044adfedec3fed639402a0a1ec2deb6253d

File: plugins/main/public/components/common/tables/table.tsx (hunk 1 above)
Comment (Desvelao) [reply plugins/main/public/components/common/tables/table.tsx:92]: Yes, the variable could be memoized to enhance the component performance, but taking into account the pull request is related to a bug with a component that did not update, adding the memoization could cause the same problem again if this is not managed correctly. Moreover, in this case, the memoization could cause a problem in the future if some internal dependency used in the `ExpandableRowContent` component changes and this is not listed as a dependency of the `useMemo`.

I will research the memoization suggestion.

Comment (Desvelao) [reply plugins/main/public/components/common/tables/table.tsx:92]: For now, I think I will not include the memoization due to some tests I was doing.

Comment (Firefly0) [reply plugins/main/public/components/common/tables/table.tsx:92]: Thank you for the feedback! {ˆ_ˆ}

**Review by gonzaarancibia — APPROVED** [review]
### :green_circle: Test:

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test                                                                                                                                                                                                                                                                                                                                                                        | Chrome(Arc)         | Firefox        | Safari         |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------- | -------------- | -------------- |
| In Configuration Assessment > Dashboard, see acheck policy expanding the row, ensure the SCA policy eas executed and the check result changed, then click on the Refresh button. The expanded row should be collapsed and you should see the new result for the check (if this is in the page 1, else you should navigate). Expand the row should display the updated data. | :green_circle: | :green_circle: | :green_circle: |
| In Configuration Assessment > Dashboard, clicking on the table rows of the policy checks should expand the row and display more information.                                                                                                                                                                                                                                | :green_circle: | :green_circle: | :green_circle: |
| In Configuration Assessment > Dashboard, clicking on the button of the row that expands it should expand the row and display more information.                                                                                                                                                                                                                              | :green_circle: | :green_circle: | :green_circle: |
| In all the modules of Regulatory compliance/MITRE ATT&CK > Controls, open the flyout details, and expand rows of the table, changing the page or refreshing the query, should collapse the expanded rows.                                                                                                                                                                   | :green_circle: | :green_circle: | :green_circle: |
| In all the modules of Regulatory compliance/MITRE ATT&CK > Controls, open the flyout details, clicking on the expand row button should expand the event with more information.                                                                                                                                                                                              | :green_circle: | :green_circle: | :green_circle: |
| In Security > Roles > Edit role flyout, clicking on the expand row button, should expand the row.                                                                                                                                                                                                                                                                           | :green_circle: | :green_circle: | :green_circle: |

**Details**

<details>
<summary>:green_circle: In Configuration Assessment > Dashboard, see acheck policy expanding the row, ensure the SCA policy eas executed and the check result changed, then click on the Refresh button. The expanded row should be collapsed and you should see the new result for the check (if this is in the page 1, else you should navigate). Expand the row should display the updated data.</summary>

Chrome(Arc) - :green_circle:

https://github.com/user-attachments/assets/83df816c-76ec-49b8-a922-0a1e59aff693


Firefox - :green_circle::
<img width="1774" alt="Screenshot 2025-06-24 at 6 51 55 AM" src="https://github.com/user-attachments/assets/8e22179c-d6ca-4c75-9060-4841139008ab" />
<img width="1776" alt="Screenshot 2025-06-24 at 6 53 27 AM" src="https://github.com/user-attachments/assets/ac2bad26-c708-4a5e-a484-c4a6e9c731c0" />


Safari - :green_circle::
<img width="1770" alt="Screenshot 2025-06-24 at 6 53 59 AM" src="https://github.com/user-attachments/assets/093d6841-3203-4573-a9fc-fdb3ecdda091" />
<img width="1768" alt="Screenshot 2025-06-24 at 6 54 52 AM" src="https://github.com/user-attachments/assets/73586fc1-fef6-4863-b8bd-8de98faa61f9" />

</details>

<details>
<summary>:green_circle: In Configuration Assessment > Dashboard, clicking on the table rows of the policy checks should expand the row and display more information.</summary>

Chrome(Arc) - :green_circle:


https://github.com/user-attachments/assets/391a5bfa-bc4d-4a1a-afcf-a36e00ad19e6


Firefox - :green_circle:

https://github.com/user-attachments/assets/78fb010a-9661-43ac-881d-3142018a27e0


Safari - :green_circle:

https://github.com/user-attachments/assets/2a08213a-df4a-4810-a905-616f504faf8a


</details>

<details>
<summary>:green_circle: In Configuration Assessment > Dashboard, clicking on the button of the row that expands it should expand the row and display more information.</summary>

Chrome(Arc) - :green_circle:

https://github.com/user-attachments/assets/7f8ca25b-8baf-4775-b395-06137c78f9ad


Firefox - :green_circle:

https://github.com/user-attachments/assets/e603f297-a229-48c7-89c1-def5a30626b5


Safari - :green_circle:


https://github.com/user-attachments/assets/ef1cb736-db2a-4aa6-9a53-f9ec4adba8f7



</details>

<details>
<summary>:green_circle: In all the modules of Regulatory compliance/MITRE ATT&CK > Controls, open the flyout details, and expand rows of the table, changing the page or refreshing the query, should collapse the expanded rows.</summary>

Chrome(Arc) - :green_circle:

https://github.com/user-attachments/assets/5895e3a2-8f17-4c52-84bb-b52b3ea4c32e


Firefox - :green_circle:

https://github.com/user-attachments/assets/0680098a-0ed8-4f1c-ad96-c20908737494


Safari - :green_circle:

https://github.com/user-attachments/assets/f4e2621b-edca-489c-b230-d25c33279a7d


</details>

<details>
<summary>:green_circle: In all the modules of Regulatory compliance/MITRE ATT&CK > Controls, open the flyout details, clicking on the expand row button should expand the event with more information.</summary>

Chrome(Arc) - :green_circle:
https://github.com/user-attachments/assets/5895e3a2-8f17-4c52-84bb-b52b3ea4c32e

Firefox - :green_circle:
https://github.com/user-attachments/assets/0680098a-0ed8-4f1c-ad96-c20908737494

Safari - :green_circle:
https://github.com/user-attachments/assets/f4e2621b-edca-489c-b230-d25c33279a7d

</details>

<details>
<summary>:green_circle: In Security > Roles > Edit role flyout, clicking on the expand row button, should expand the row.</summary>

Chrome(Arc) - :green_circle:

https://github.com/user-attachments/assets/3257d708-93d3-43c1-af5a-4392cef3b97a


Firefox - :green_circle:

https://github.com/user-attachments/assets/fe0d79e9-8740-4644-8d69-92b921a7afce


Safari - :green_circle:

https://github.com/user-attachments/assets/ce61d78b-282b-439b-932a-8dce5a2a4ad4

**Comment by guidomodarelli** [comment]
### 🟢 Test Legend

| Symbol | Meaning                                                              |
| ------ | -------------------------------------------------------------------- |
| ⚫      | The test hasn't started yet.                                         |
| 🟢     | All checks passed.                                                   |
| 🟡     | There is at least one expected fail or skipped test and no failures. |
| 🔴     | There is at least one failed check.                                  |
| ⚪      | Doesn't apply.                                                       |
| 🔧     | Request changes.                                                     |
| ❓      | Needs more information.                                              |

---

## 🧪 UI Tests

| Test Description                                                                                                                                                                                                                                                                 | Chrome | Firefox |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ | ------- |
| 1️⃣ In **Configuration Assessment > Dashboard**: Expand a check policy row → Ensure the SCA policy executed and check result changed → Click **Refresh** → Row should collapse and display updated result (navigate if not on page 1) → Expanding again should show updated data | 🟢      | ⚫       |
| 2️⃣ In **Configuration Assessment > Dashboard**: Click on a policy check row → Row should expand and display more information                                                                                                                                                    | 🟢      | ⚫       |
| 3️⃣ In **Configuration Assessment > Dashboard**: Click on the expand-row button of a policy check → Row should expand and display more information                                                                                                                               | 🟢      | ⚫       |
| 4️⃣ In **Regulatory Compliance / MITRE ATT\&CK > Controls**: Open flyout details → Expand rows in table → Change page or refresh query → All expanded rows should collapse                                                                                                       | 🟢      | ⚫       |
| 5️⃣ In **Regulatory Compliance / MITRE ATT\&CK > Controls**: Open flyout details → Click expand-row button → Event should expand with more information                                                                                                                           | 🟢      | ⚫       |
| 6️⃣ In **Security > Roles > Edit role flyout**: Click expand-row button → Row should expand                                                                                                                                                                                      | 🟢      | ⚫       |

---

### 📋Test Details

<details><summary> 🟢 1️⃣ In **Configuration Assessment > Dashboard**: Expand a check policy row → Ensure the SCA policy executed and check result changed → Click **Refresh** → Row should collapse and display updated result (navigate if not on page 1) → Expanding again should show updated data</summary>
  <br />

> **CHROME** - 🟢
>
> ![image](https://github.com/user-attachments/assets/95796b81-bb41-424c-b1cf-3e7f8f347282)
> ![Screenshot 2025-06-26 140058](https://github.com/user-attachments/assets/3c126513-6d6c-4770-925b-5b5adce18789)

> **FIREFOX** - ⚫

</details>

<details><summary> 🟢 2️⃣ In **Configuration Assessment > Dashboard**: Click on a policy check row → Row should expand and display more information</summary>
  <br />

> **CHROME** - 🟢
>
> https://github.com/user-attachments/assets/f9e611b6-781e-4a47-af18-79d1fca1b693

> 

> **FIREFOX** - ⚫

</details>

<details><summary> 🟢 3️⃣ In **Configuration Assessment > Dashboard**: Click on the expand-row button of a policy check → Row should expand and display more information</summary>
  <br />

> **CHROME** - 🟢
>
> https://github.com/user-attachments/assets/466e44bb-004e-4e2f-b31b-203ba434675a

> **FIREFOX** - ⚫

</details>

<details><summary> 🟢 4️⃣ In **Regulatory Compliance / MITRE ATT&CK > Controls**: Open flyout details → Expand rows in table → Change page or refresh query → All expanded rows should collapse</summary>
  <br />

> **CHROME** - 🟢
>
> https://github.com/user-attachments/assets/332bb951-a1b7-42a4-bb45-d57fbd9be5c8

> **FIREFOX** - ⚫

</details>

<details><summary>🟢 5️⃣ In **Regulatory Compliance / MITRE ATT&CK > Controls**: Open flyout details → Click expand-row button → Event should expand with more information</summary>
  <br />

> **CHROME** - 🟢
> 
> https://github.com/user-attachments/assets/e5986d95-c6ab-4b80-8a92-844b0ec4fb4d

> **FIREFOX** - ⚫

</details>

<details><summary>🟢 6️⃣ In **Security > Roles > Edit role flyout**: Click expand-row button → Row should expand</summary>
  <br />

> **CHROME** - 🟢
>
> https://github.com/user-attachments/assets/fc89fa55-3226-4d8f-a3a5-4ab483f8b1dd

> **FIREFOX** - ⚫

</details>

**Review by guidomodarelli — APPROVED** [review]
LGTM! 🟢
