### PR TITLE
Fix switching tabs in the same module encodes the url

### LINKED ISSUE #6773: Switching tabs in the same module encodes the URL
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | Chrome, Firefox, Safari |

# Description

When the user clicks on the Dashbords or Events tab the URL special characters get encoded. We need to fix this so that the string of filters applied is represented the same way OpenSearch does.

## Screenshot

Peek 2024-06-14 10-55

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

Fix the url encoding.
 
### Issues Resolved

#6773 

### Modules
https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/f2978066-12f6-4dbe-9897-03a215bee836

### Rules
image

### Endpoint summary > Configuration > Endpoint groups

https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/18d2cd59-74d0-4c1b-ad07-51a021ee81a0

### Health-check

https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/b26c3cf3-c660-457a-9d02-a666451c67bf

### FIM Inventory tab table

https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/f9a81a49-48c4-4f06-b3b7-315841e3aa01

### Test

Verify that in the parts shown in the video evidence the url is not encoded, update and remove the url parameters if necessary.

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: plugins/main/public/react-services/navigation-service.tsx [hunk 1]
```diff
@@ -124,6 +124,34 @@ class NavigationService {
     return getCore().application.getUrlForApp(appId, options);
   }
 
+  public switchTab(newTab: any, force: any) {
```
Comment (jbiset) [inline plugins/main/public/react-services/navigation-service.tsx:127]: `newTab` is supposed to be of type string and force I understand is a `boolean`, although `force` is not necessary there since it is not used. Right?
It's a minor change but it can prevent errors from passing incorrect parameters.

File: plugins/main/public/react-services/navigation-service.tsx [hunk 2]
```diff
@@ -124,6 +124,34 @@ class NavigationService {
...
+    urlSearchParams.set('tab', newTab);
+    this.navigate(
+      `${this.getPathname()}?${urlSearchParams
+        .entries()
+        .reduce(
+          (total, current) =>
+            (total += `${total ? '&' : ''}${current[0]}=${current[1]}`),
+          '',
+        )}`,
+    );
```
Comment (jbiset) [inline plugins/main/public/react-services/navigation-service.tsx:138]: `urlSearchParams.entries().reduce` generates a problem since `urlSearchParams.entries()` returns an `Iterable` and `reduce` is an array method. In Google this does not seem to cause a problem, but in Firefox it does. A possible solution may be to leave it as follows:

```typescript
const urlSearchParamsEntries = Array.from(urlSearchParams.entries());
this.navigate(
  `${this.getPathname()}?${urlSearchParamsEntries.reduce(
    (total: string, current: string) =>
      `${total}${total ? '&' : ''}${current[0]}=${current[1]}`,
    '',
  )}`,
    );
```

File: plugins/main/public/react-services/navigation-service.tsx [hunk 3]
```diff
@@ -124,6 +124,34 @@ class NavigationService {
...
+    urlSearchParams.set('tabView', subTab);
+    this.navigate(
+      `${this.getPathname()}?${urlSearchParams
+        .entries()
+        .reduce(
+          (total, current) =>
+            (total += `${total ? '&' : ''}${current[0]}=${current[1]}`),
+          '',
+        )}`,
+    );
```
Comment (jbiset) [inline plugins/main/public/react-services/navigation-service.tsx:152]: It's the same case as the previous comment.

**Review by jbiset — CHANGES_REQUESTED** [review]
## CR: :red_circle: (Comments added)

## Test UI :red_circle: 

### Chrome :green_circle: 

[Evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/b6b55dbf-0a4d-4149-96ca-46c7e9654c76)


### Firefox :red_circle: 

image

**Comment by JuanGarriuz** [comment]
### Test 🟢 

<details><summary>Evidence 🟢 </summary>

#### Chrome

https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/fff32be9-8efe-4b2f-b9d7-148b832bd12f



</details>

**Comment by chantal-kelm** [comment]
> Some navigations are using the `URLSearchParams` constructor and composing the URL search parameters with the `.toString` method. According to the changes, it seems the fix is replace the usage of `.toString()` by a custom method to built the URL search parameters.
> 
> I guess this problem could appear in the remaining navigations that are using the `URLSearchParamters.prototype.toString()` method. In this case we should adapt too. For extension, we could create a custom constructor similar to URLSearchParameters with the implementation of URL search parameters build.

As mentioned in this comment it was decided to make a more global solution that attacks all files with the same problem.

I am working on it.

File: plugins/main/public/react-services/navigation-service.tsx (hunk 1 above)
Comment (chantal-kelm) [reply plugins/main/public/react-services/navigation-service.tsx:127]: Resolved in this [commit]([449abd7](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6775/commits/449abd7f000be516ccb589d78c6b1af7348dd746))

File: plugins/main/public/react-services/navigation-service.tsx (hunk 2 above)
Comment (chantal-kelm) [reply plugins/main/public/react-services/navigation-service.tsx:138]: It was decided to make a solution that fits all cases and in one of the methods to use the 'Array from' suggested

File: plugins/main/public/react-services/navigation-service.tsx (hunk 3 above)
Comment (chantal-kelm) [reply plugins/main/public/react-services/navigation-service.tsx:152]: It was decided to make a solution that fits all cases and in one of the methods to use the 'Array from' suggested

File: plugins/main/public/react-services/navigation-service.tsx [hunk 4]
```diff
@@ -124,6 +124,44 @@ class NavigationService {
...
 
+  public buildSearch(search: URLSearchParams) {
+    return Array.from(search.entries())
+      .map(([key, value]) => `${key}=${value}`)
+      .join('&');
+  }
+
+  public updateAndNavigateSearchParams(
+    updateParams: { [key: string]: string | undefined },
+    deleteParams: string[] = [],
```
Comment (Desvelao) [inline plugins/main/public/react-services/navigation-service.tsx:135]: **suggestion**: you could simplify the logic using only a parameter of object type. If the value of a key is `null`, then the parameter could be considered to be removed.

Example of usage:

```
navigationService.updateAndNavigateSearchParams({
  param1: null,
});
```

**Review by JuanGarriuz — APPROVED** [review]

File: plugins/main/public/react-services/navigation-service.tsx (hunk 4 above)
Comment (chantal-kelm) [reply plugins/main/public/react-services/navigation-service.tsx]: This has been done in this commit [363c107](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6775/commits/363c10731ff2d0de23ecfbcdd013cc2bb072280c)

**Review by jbiset — APPROVED** [review]
## CR: :green_circle: 

## Test UI: :green_circle: 

### Modules :green_circle: 

**Chrome**

[Evidence1_Chrome.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/c51e860c-6a28-49cb-8669-01cca9338855)

**Firefox**

[Evidence1_Firefox.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/8045874f-c6db-4117-8cf2-5767ad7f8046)

### Rules :green_circle: 

**Chrome**

image

**Firefox**

image

### Endpoint summary > Configuration > Endpoint groups :green_circle: 

**Chrome**

[Evidence3_Chrome.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/4ea13a6f-215c-4085-b83e-ea0420bb1b77)

**Firefox**

[Evidence3_Firefox.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/7038dd25-a224-4bf4-90a8-eeec33b2bcb2)

### Health-check :green_circle: 

**Chrome**

[Evidence4_Chrome.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/e102ac8d-5880-4c11-8f00-46fec99323a8)

**Firefox**

[Evidence4_Firefox.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/210d625d-e8ab-4e5e-a223-07d4acbf4aeb)


### FIM Inventory tab table :green_circle: 

**Chrome**


[Evidence5_Chrome.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/c8696052-4dfb-44ed-ac48-825c81ff07ad)

**Firefox**

[Evidence5_Firefox.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/783d5479-4400-4573-bcf7-b7b53d1993bc)

**Review by Desvelao — APPROVED** [review]
LGTM!

**Review by JuanGarriuz — APPROVED** [review]
LGTM!!
