### PR TITLE
Adapt the navigation between applications

### LINKED ISSUE #5900: Problems switching between modules and agents applications
Some problems have been found,
- [x] When you change application quickly, sometimes it gives you an error in the console and shows you the previous view to the currently selected one.

<details><summary>screenshot</summary>

image

</details> 

- [x] Sometimes when you want to enter to some module it always redirects you to the Endpoints summary.
<details><summary>screenshot</summary>

image

</details> 

- [x] Problems with the tabView in the url, in the views you should change the value but then returns to the previous value.
<details><summary>screenshot</summary>

image

image

</details> 

- [x] When navigating to an agent from the agent table is not working

- [x] In the Statistics plugin the same thing is happening with the settings button, it redirects to a wazuh-plugin-settings and should redirect to settings.

https://github.com/wazuh/wazuh-dashboard-plugins/blob/feat/83-move-menu-items-to-applications/plugins/main/public/controllers/management/components/management/statistics/statistics-overview.js#L203

- [x] redirection of an agent to some group as it has to redirect to the groups plugin and is trying to go to endpoint-group.

https://github.com/wazuh/wazuh-kibana-app/blob/feat/83-move-menu-items-to-applications/plugins/main/public/components/common/util/agent-group-truncate/group-truncate.tsx#L55

https://github.com/wazuh/wazuh-kibana-app/blob/feat/83-move-menu-items-to-applications/plugins/main/public/controllers/management/components/management/configuration/configuration-switch.js#L214

Problem 1 and 2 may be related because it occurs when you click twice in a row on the endpoint summary and then want to go to another module, or click twice in a row on a module and navigate to the endpoint summary.

- [x] adapt the navigation between the applications

_Originally posted by @yenienserrano in https://github.com/wazuh/wazuh-kibana-app/issues/5820#issuecomment-1706933114_

- [x] Whenever a user uses OpenSearch new _Discover_ plugin the browser console throws an exception

<details>

<summary> Error: ScopedHistory instance has fell out of navigation scope for basePath </summary>

### How to replicate the issue:

- Go to the new Discover plugin
image

- Go to Threat Hunting module (_or any dashboard module_)
- See the error in the console

The exception is thrown in the Scope History class of the Core features of the platform and it doesn't seem to break the expected use of the Dashboards or Events tabs.

This issue has been reported in OpenSearch and seems to be due to an incompatibility between the **_Legacy Discover_** and the **_New Discover_** plugin. 

**OpenSearch will not fix this error because will deprecate the Legacy Discover in version 2.11.0.** The course of action to be taken is to deprecate Wazuh Kibana Discover module in a future release.

### OpenSearch issue
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4698

## Screenshot

image

</details>

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request adapts the navigation between the applications.
 
### Issues Resolved
#5900 

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: plugins/main/public/controllers/management/monitoring.js [hunk 1]
```diff
@@ -81,7 +80,7 @@ export function ClusterController(
    * This navigates to agents preview
    */
   $scope.goAgents = () => {
-    navigateAppURL('/app/endpoints-summary#/agents-preview/?');
+    getCore().application.navigateToApp('endpoints-summary');
```
Comment (yenienserrano) [inline plugins/main/public/controllers/management/monitoring.js:83]: may be missing `#/agents-preview/`?

**Review by yenienserrano — APPROVED** [review]
LGTM
